name: flutter_vechain
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dio: ^2.0.9
  # 轮播图插件
  flutter_swiper : ^1.1.6
  # 屏幕适配插件
  flutter_screenutil: ^0.5.2
  # 设置APP图标插件
  flutter_launcher_icons: ^0.6.1
  # 启动电话 短信 浏览器插件
  url_launcher: ^5.0.2
  # 状态管理插件
  provide: ^1.0.2
  # 上拉刷新加载插件
  flutter_easyrefresh: ^1.2.7
  # 轻提示插件
  fluttertoast: ^3.0.4
  # 路由插件
  fluro: ^1.4.0
  # 以太坊web3 dart包
  web3dart: ^0.4.5
  # 操作sqlite
  sqflite: ^1.1.0
  # 扫描二维码
  barcode_scan: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "images/wallet.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/ethereum.jpg
   - images/ethereum.png
   - images/vechain.jpg
   - images/vechain.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: selfIcon
      fonts:
        - asset: fonts/iconfont.ttf 
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
